using System.Diagnostics.CodeAnalysis;
using System.Text.Json.Serialization;
using Frontier.Platform.Abstractions;

namespace Frontier.Platform.Workflow.Model;

/// <summary>
/// Human approval gate (doc 00 §3.2, doc 06). Compiles to a notify activity followed by
/// <c>WaitForExternalEvent("Gate:{nodeId}")</c>; rejection triggers snapshot-based
/// rollback to <see cref="RollbackToNodeId"/>, never blind replay (doc 06).
/// </summary>
[ExcludeFromCodeCoverage(Justification = "Plain data contract; properties are exercised by S1.6 round-trip/golden-file tests.")]
public sealed record HumanGateNode : WorkflowNode
{
    /// <inheritdoc />
    [JsonIgnore]
    public override NodeType NodeType => NodeType.HumanGate;

    /// <summary>Selects default allowed decisions and UI emphasis (doc 06 §3).</summary>
    [JsonPropertyOrder(3)]
    [JsonPropertyName("gate_kind")]
    public required GateKind GateKind { get; init; }

    /// <summary>Roles whose members may decide at this gate; resolved at runtime, never user ids (doc 06 §3).</summary>
    [JsonPropertyOrder(4)]
    [JsonPropertyName("approver_roles")]
    public required IReadOnlyList<string> ApproverRoles { get; init; }

    /// <summary>What the approver is asked, rendered in the approval UI (doc 06 §3).</summary>
    [JsonPropertyOrder(5)]
    [JsonPropertyName("prompt_template")]
    public required string PromptTemplate { get; init; }

    /// <summary>Minutes before this gate escalates; <c>0</c> means no escalation (doc 06 §3).</summary>
    [JsonPropertyOrder(6)]
    [JsonPropertyName("timeout_minutes")]
    public required int TimeoutMinutes { get; init; }

    /// <summary>Rejection target node id; <c>null</c> means reject-in-place (revise &amp; resubmit) (doc 06 §3).</summary>
    [JsonPropertyOrder(7)]
    [JsonPropertyName("rollback_to_node_id")]
    public string? RollbackToNodeId { get; init; }

    /// <summary>Whether sections regenerated by a cascade must re-enter this gate (doc 03 §9). Defaults to <c>true</c>.</summary>
    [JsonPropertyOrder(8)]
    [JsonPropertyName("reapprove_on_cascade")]
    public bool ReapproveOnCascade { get; init; } = true;
}
